### ISSUE TITLE
パンフレット（栞作成）

### ISSUE THREAD

**Issue by kazuki1023** [kazuki1023/hackathon_management#16]
- ハッカソンの開会式でメンバーに配布する
>- ブランディングに依頼ってことでよろしい？？？？

**Comment by hiratemiyu** [comment]
いいよ！

**Comment by hiratemiyu** [comment]
> * ハッカソンの開会式でメンバーに配布する
> 
> > * ブランディングに依頼ってことでよろしい？？？？

いいよ

**Comment by hiratemiyu** [comment]
中間発表あり
canva、前のやつをコピペ
2/14 午前～　作成
